collection:
  deduplicate: false
  log_level: INFO
  output_dir: data
  output_file: ascend_model.json
  sort_by_stars: true

gitcode:
  groups:
    - name: AI4Science
      org_id: AI4Science
    - name: ai-ascend-models
      org_id: ai-ascend-models
    - name: ascend-tribe
      org_id: ascend-tribe
    - name: Ascend-SACT
      org_id: Ascend-SACT

